# Generated by Django 5.1.3 on 2024-11-10 16:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_complete', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('publisher', models.CharField(max_length=100)),
                ('authors', models.CharField(max_length=255)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('num_pages', models.IntegerField(blank=True, null=True)),
                ('isbn', models.CharField(blank=True, max_length=10, null=True)),
                ('isbn13', models.CharField(blank=True, max_length=13, null=True)),
                ('genres_vector', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
                ('recommended_books', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('genres', models.ManyToManyField(related_name='books', to='books.genre')),
            ],
        ),
    ]
